# Generated by Django 4.2.7 on 2023-11-25 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_perfilestudiante_idperfilestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidades',
            fields=[
                ('fechaCreada', models.DateTimeField(auto_created=True)),
                ('idComunidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComunidad', models.CharField(max_length=144)),
                ('descripcionComunidad', models.TextField()),
                ('cedulaCreador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
