# Generated by Django 4.2.7 on 2023-11-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_perfilestudiante_idperfilestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('fechaPublicacion', models.DateTimeField(auto_created=True)),
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('tituloPublicacion', models.CharField(max_length=100)),
                ('descripcionPublicacion', models.TextField()),
                ('tipoPublicacion', models.CharField(max_length=100)),
                ('cedulaCreador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
