# Generated by Django 4.2.7 on 2023-12-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_capitulospublicacion_descripcioncapitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulospublicacion',
            name='nada',
            field=models.CharField(default='nada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitulospublicacion',
            name='miniatura',
            field=models.FileField(upload_to='miniaturaVideo/'),
        ),
    ]
