# Generated by Django 4.2.7 on 2023-12-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_capitulospublicacion_nada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulospublicacion',
            name='miniatura',
        ),
        migrations.RemoveField(
            model_name='capitulospublicacion',
            name='nada',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='miniatura',
        ),
    ]
