# Generated by Django 4.2.7 on 2023-12-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_remove_capitulospublicacion_miniatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulospublicacion',
            name='video_url',
            field=models.FileField(upload_to='capitulos/'),
        ),
    ]
