# Generated by Django 4.2.7 on 2023-12-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_alter_capitulospublicacion_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulospublicacion',
            name='miniatura',
            field=models.FileField(default='nada', upload_to='videos/miniatura/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='miniatura',
            field=models.FileField(default='nada', upload_to='miniatura/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitulospublicacion',
            name='video_url',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
