# Generated by Django 4.2.7 on 2023-12-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0007_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='idPublicacion',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='idCapituloPublicacion',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='publicacion.capitulospublicacion'),
            preserve_default=False,
        ),
    ]
