# Generated by Django 4.2.7 on 2023-12-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0008_remove_comentarios_idpublicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='miniatura',
            field=models.ImageField(upload_to='miniatura/'),
        ),
    ]
