# Generated by Django 4.2.7 on 2023-12-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuarios_nada'),
        ('publicacion', '0009_alter_publicacion_miniatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursosIniciados',
            fields=[
                ('idCursoIniciado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('cedulaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
                ('idPublicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacion.publicacion')),
            ],
        ),
    ]
