# Generated by Django 4.2.7 on 2023-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('idEscuela', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombreEscuela', models.CharField(max_length=100)),
            ],
        ),
    ]
