# Generated by Django 4.2.7 on 2023-11-03 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('correo_electronico', models.CharField(max_length=244, unique=True)),
                ('nombre', models.CharField(max_length=244)),
                ('apellido', models.CharField(max_length=244)),
                ('usuario', models.CharField(max_length=244)),
                ('rol', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('idPerfilEstudiante', models.CharField(primary_key=True, serialize=False)),
                ('semestreEstudiante', models.CharField(max_length=100)),
                ('cedulaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios', unique=True)),
                ('escuelaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.escuela')),
            ],
        ),
    ]
