# Generated by Django 4.2.7 on 2023-11-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilestudiante',
            name='cedulaEstudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='PerfilProfesor',
            fields=[
                ('idPerfilProfesor', models.AutoField(primary_key=True, serialize=False)),
                ('experienciaProfesor', models.CharField(max_length=244)),
                ('materiaProfesor', models.CharField(max_length=244)),
                ('fraseProfesor', models.CharField(max_length=244)),
                ('sobreProfesor', models.CharField(max_length=244)),
                ('cedulaProfesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
