# Generated by Django 4.2.7 on 2023-11-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('correo_electronico', models.CharField(max_length=244, unique=True)),
                ('nombre', models.CharField(max_length=244)),
                ('apellido', models.CharField(max_length=244)),
                ('usuario', models.CharField(max_length=244)),
                ('rol', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=244)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
