# Generated by Django 4.2.7 on 2023-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuarios_apellido_remove_usuarios_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
