# Generated by Django 4.2.7 on 2023-12-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarios_nada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nada',
        ),
    ]
